import { test } from 'node:test';
import assert from 'node:assert/strict';
import { must } from './helpers.ts';
import { deflateRawSync, inflateRawSync } from 'node:zlib';
import { loadData } from '../src/data.ts';
import { applySharedChoices, defaultState, migrate } from '../src/state.ts';
import { decodeShare, encodeShare, sharedChoices, shareKey, shareUrl, ShareCodeError, type SharedChoices } from '../src/share.ts';
import { GOAL_TEMPLATES } from '../src/model/goal-templates.ts';
import { planRun, unavailableRunChoices } from '../src/model/run.ts';

const data = loadData();
// Literal expected defaults and historical codes are compatibility fixtures, not generated by the codec under test.
const empty: SharedChoices = {
  run: {
    traineeCardId: null, traineeStars: 3,
    goal: { blueStats: ['speed', 'stamina', 'power', 'guts', 'wit'], blueStars: 2, pink: [{ aptitude: 'any', stars: 1 }] },
    targets: [], targetLineage: {}, parentSparks: [[null, null, null], [null, null, null]],
    pinkLineage: [null, null, null, null, null, null], aptOverrides: {}, pinnedIds: [], borrowFromAll: false,
    wishlistOrder: [], wishlistExcluded: [], raceOverrides: {}, ignoredIds: [], borrowIgnored: false,
  },
  settings: { focus: 'stamina', winThreshold: 0.8 },
};
const populated: SharedChoices = {
  run: {
    traineeCardId: 100101, traineeStars: 4,
    goal: { blueStats: ['speed', 'power'], blueStars: 3, pink: [{ aptitude: 'mile', stars: 2 }] },
    targets: [{ id: 201601, role: 'required', stars: 3, priority: 0 }],
    targetLineage: { 201601: [3, 2, 0, 3, 0, 0] },
    parentSparks: [[{ stat: 'speed', stars: 3 }, null, { stat: 'power', stars: 2 }], [null, null, null]],
    pinkLineage: [{ aptitude: 'mile', stars: 3, inferred: true }, null, null, null, null, null],
    aptOverrides: { mile: 'A' }, pinnedIds: [30160], borrowFromAll: true,
    wishlistOrder: [201601, 200472], wishlistExcluded: [200012], raceOverrides: {}, ignoredIds: [], borrowIgnored: false,
  },
  settings: { focus: 'sprint', winThreshold: 0.65 },
};
const prototype = '1dfZDBasMwEET_Zc5DkeQkhb31G3oUOqRYBWHXUSWZUIT-vShu3PTSy8KyM4-ZtUZRK6WV5oEVb_PqX8u5ZIhFjt6PIOLl6hMc79eUIQMRwzJBbMU5llDW0UPwEWYPIm8i01yjrQgjxCh9UppIl7kLk_9cQ7rh8y8xhUsK5QuimmPF5oFUTBpiiMlANBE15EhEAxlao7W1Qwpkj3xnNi7rPHO_b1UeA9LeFPtwjv9VGoiwvPvUo0tJq2_8638gsW5mwQsa7dDbOHYT7c87jFKHZ-P6rpQ2jsgxhaWA6ul0dN8';
const plain = (raw: unknown) => `2j${Buffer.from(JSON.stringify(raw)).toString('base64url')}`;

const legacy = (choices: SharedChoices) => {
  const copy = structuredClone(choices);
  delete copy.run.raceOverrides;
  return copy;
};

test('historical share fixtures retain their original choices independently of app defaults', async () => {
  assert.deepEqual(await decodeShare('2jW10'), legacy(empty));
  assert.deepEqual(await decodeShare('1jWzIwXQ'), legacy(empty));
  assert.deepEqual(await decodeShare(prototype), legacy(populated));
  assert.deepEqual(await decodeShare('2dTYzRDUJBEAIbmhjYvXvay4b-2zBnnsbwBQyMJcssZtPMLCoJMyVfMqLRf1CYTX-iRrzCCN1Q0zjoq5s6XZ99ML8naT0rx0uuUOhx7bwB'), legacy(populated));
});

test('frozen format 3 fixtures retain defaults and signed schedule overrides', async () => {
  assert.deepEqual(await decodeShare('3jW10'), empty);
  const code = '3dTYzZDcMwDEMXeikoyXbbWQTuv0bgIClKfvHskELBoCdF9yBt052KpUAU-jeSYFKXVYiPaaG7VBRh9PBu7az23gS_J2m801tLkSbRa036WFmsHBzfC_YJ';
  const expected: SharedChoices = {
    ...populated,
    run: { ...populated.run, raceOverrides: { 623: false, 624: true, 999999: false } },
  };
  assert.deepEqual(await decodeShare(code), expected);
});

test('compact shares round-trip every curated template and shorten representative codes', async () => {
  for (const template of GOAL_TEMPLATES) {
    const state = defaultState(data);
    Object.assign(state.run, structuredClone({ goal: template.goal, targets: template.targets, targetLineage: template.targetLineage ?? {} }));
    const choices = sharedChoices(state), code = await encodeShare(choices);
    assert.deepEqual(await decodeShare(code), choices, template.id);
    assert.ok(code.length < JSON.stringify(choices).length, `${template.id}: compact code is smaller than the named fields`);
  }
  const code = await encodeShare(populated);
  assert.ok(code.length < prototype.length, `compact code ${code.length} chars vs prototype ${prototype.length}`);
  assert.deepEqual(await decodeShare(code), populated);
});

test('partial inputs, boundaries, explicit empty choices and inactive lineage survive', async () => {
  const input = structuredClone(empty);
  input.run.traineeStars = 1;
  input.run.goal = { blueStats: [], blueStars: 1, pink: [{ aptitude: 'end', stars: 3 }, { aptitude: 'dirt', stars: 1 }] };
  input.run.targets = [{ id: 99999991, role: 'preferred', stars: 1, priority: Number.MAX_SAFE_INTEGER }];
  input.run.targetLineage = { 99999992: [0, 0, 0, 3, 3, 3] };
  input.run.targetLineage['99999993'] = [0, 2, 0, 0, 0, 1];
  input.run.aptOverrides = { end: 'G', turf: 'A', mile: 'D' };
  input.run.parentSparks[1] = [{ stat: 'wit', stars: 3 }, { stat: 'stamina', stars: 1 }, { stat: 'guts', stars: 2 }];
  input.run.pinkLineage[5] = { aptitude: 'end', stars: 1 };
  input.settings = { focus: 'balanced', winThreshold: 0 };
  assert.deepEqual(await decodeShare(await encodeShare(input)), input);
  input.settings.winThreshold = 1;
  input.run.traineeStars = 5;
  assert.deepEqual(await decodeShare(await encodeShare(input)), input);
});

test('share scope excludes inventory, advanced settings, theme, and cached results', async () => {
  const local = defaultState(data);
  local.inventory = { 30160: 1, 30001: null };
  local.settings.affinity = 222;
  local.ui.theme = 'dark';
  local.run.raceOverrides = { '999999': false };
  const before = structuredClone(local);
  const key = shareKey(sharedChoices(local));
  local.inventory[30002] = 3; local.settings.affinity = 180; local.ui.theme = 'light';
  assert.equal(shareKey(sharedChoices(local)), key);
  applySharedChoices(before, await decodeShare(prototype));
  assert.deepEqual(sharedChoices(before), { ...populated, run: { ...populated.run, raceOverrides: { '999999': false } } });
  assert.deepEqual(before.inventory, { 30160: 1, 30001: null });
  assert.equal(before.settings.affinity, 222);
  assert.equal(before.ui.theme, 'dark');
  assert.deepEqual(before.run.raceOverrides, { '999999': false });
  assert.deepEqual(migrate({ current: before }, data), before);
});

test('equivalent record insertion orders generate the same code', async () => {
  const a = structuredClone(populated), b = structuredClone(populated);
  a.run.aptOverrides = { mile: 'A', end: 'G' }; b.run.aptOverrides = { end: 'G', mile: 'A' };
  assert.equal(await encodeShare(a), await encodeShare(b));
});

test('removed, renamed and reclassified game data cannot change stored share choices', async () => {
  const choices = structuredClone(populated);
  choices.run.pinnedIds = [30052];
  const local = defaultState(data);
  applySharedChoices(local, choices);
  const changed = { ...data, skillById: new Map(data.skillById), cardById: new Map(data.cardById), charByCardId: new Map(data.charByCardId) };
  changed.skillById.delete(201601); changed.cardById.delete(30052); changed.charByCardId.delete(100101);
  let restored = migrate({ current: local }, changed);
  assert.deepEqual(sharedChoices(restored), choices);
  assert.deepEqual(unavailableRunChoices(restored.run, changed), { trainee: 100101, cards: [30052], skills: [201601] });
  assert.deepEqual(await decodeShare(await encodeShare(sharedChoices(restored))), choices);
  const original = must(data.skillById.get(201601), `data.skillById.get(201601)`);
  changed.skillById.set(original.id, { ...original, name: 'Renamed skill' });
  restored = migrate({ current: restored }, changed);
  assert.deepEqual(sharedChoices(restored), choices);
  changed.skillById.set(original.id, { ...original, unreleasedEn: true, versions: [] });
  assert.deepEqual(sharedChoices(migrate({ current: restored }, changed)), choices);
  assert.ok(unavailableRunChoices(restored.run, changed).skills.includes(original.id));
  assert.deepEqual(unavailableRunChoices(restored.run, data), { trainee: null, cards: [], skills: [] });
});

test('unavailable required targets are ignored by calculations without deleting them', () => {
  const local = defaultState(data);
  applySharedChoices(local, populated);
  local.run.targets.push({ id: 99999991, role: 'required', stars: 3, priority: 0 });
  local.run.wishlistOrder.push(99999991); local.run.wishlistExcluded.push(99999992);
  local.run.targetLineage['99999991'] = [3, 3, 3, 3, 3, 3];
  const before = structuredClone(local);
  const result = planRun(local.run, local.settings, local.inventory, data, { search: false });
  const available = structuredClone(local.run);
  available.targets.pop();
  const expected = planRun(available, local.settings, local.inventory, data, { search: false });
  assert.deepEqual(result.goalEstimate, expected.goalEstimate);
  assert.deepEqual(local, before);
  assert.deepEqual(sharedChoices(migrate({ current: local }, data)), sharedChoices(local));
});

test('malformed codes fail before any choices can be applied', async () => {
  const badPayloads: unknown[] = [null, {}, [0], [null, 6], [null, null, [32, 2, [[0, 1]]]],
    [null, null, [31, 2, [[99, 1]]]], [null, null, [31, 2, [[0, 1], [1, 2]]]],
    [null, null, null, [[201601, 3, 2, 0]]], [null, null, null, [[1.5, 0, 2, 0]]],
    [null, null, null, [[1, 0, 4, 0]]], [null, null, null, [[1, 0, 2, -1]]],
    [null, null, null, [[1, 0, 2, 0], [1, 1, 2, 0]]],
    [null, null, null, null, [[1, 1, 0, 10, 0]]],
    [null, null, null, null, null, [[1, 0], [0, 0, 0]]],
    [null, null, null, null, null, null, [0, 0, 0, 0, 0, [10, 3, 1]]],
    [null, null, null, null, null, null, null, [[0, 9]]],
    [...Array(13).fill(null), 1.1], [...Array(14).fill(null), 1]];
  for (const code of ['', 'garbage', '2dinvalid', '2jW10=', '2jW11', prototype.slice(0, -3), ...badPayloads.map(plain)]) {
    await assert.rejects(decodeShare(code), ShareCodeError, code.slice(0, 80));
  }
  await assert.rejects(decodeShare('6jW10'), (e: unknown) => e instanceof ShareCodeError && e.reason === 'version');
  await assert.rejects(decodeShare(`1j${Buffer.from('[21]').toString('base64url')}`), (e: unknown) => e instanceof ShareCodeError && e.reason === 'version');
});

test('decoder bounds both the incoming code and decompressed size', async () => {
  const bomb = `2d${deflateRawSync(Buffer.from(' '.repeat(100001))).toString('base64url')}`;
  for (const code of ['2j' + 'A'.repeat(16000), bomb]) {
    await assert.rejects(decodeShare(code), (e: unknown) => e instanceof ShareCodeError && e.reason === 'size');
  }
});

test('share URLs preserve unrelated URL parameters and fragments', () => {
  const url = shareUrl('https://example.com/planner/?theme=dark#goal', '2jW10');
  assert.equal(url, 'https://example.com/planner/?theme=dark&run=2jW10#goal');
  assert.equal(shareUrl(url, null), 'https://example.com/planner/?theme=dark#goal');
});

test('format 4 stores signed calendar IDs and replaces the whole override set', async () => {
  const choices = structuredClone(populated);
  choices.run.raceOverrides = { 624: true, 623: false, 999999: false };
  const code = await encodeShare(choices);
  assert.equal(code[0], '5');
  assert.deepEqual(await decodeShare(code), choices);
  const literal = '3j' + Buffer.from(JSON.stringify([...Array(14).fill(null), [-623, 624, -999999]])).toString('base64url');
  assert.deepEqual((await decodeShare(literal)).run.raceOverrides, choices.run.raceOverrides);
  const local = defaultState(data);
  local.run.raceOverrides = { 777: true };
  applySharedChoices(local, await decodeShare(code));
  assert.deepEqual(local.run.raceOverrides, choices.run.raceOverrides);
  assert.deepEqual(migrate({ current: local }, { ...data, races: [] }).run.raceOverrides, choices.run.raceOverrides);
  applySharedChoices(local, await decodeShare('2jW10'));
  assert.deepEqual(local.run.raceOverrides, choices.run.raceOverrides, 'older links preserve local overrides');
  applySharedChoices(local, await decodeShare('3jW10'));
  assert.deepEqual(local.run.raceOverrides, {}, 'new links with no overrides restore automatic scheduling');
  const reverse = structuredClone(choices);
  reverse.run.raceOverrides = { 999999: false, 623: false, 624: true };
  assert.equal(await encodeShare(reverse), code);
});

test('format 4 adds ignored cards in slot 15 and the borrow-ignored flag in slot 16; older codes and formats leave nothing ignored', async () => {
  const choices = structuredClone(populated);
  choices.run.ignoredIds = [30028, 30001];
  choices.run.borrowIgnored = true;
  const code = await encodeShare(choices);
  assert.equal(code[0], '5');
  assert.deepEqual(await decodeShare(code), choices);
  const slots = (code: string) => {
    const bytes = Buffer.from(code.slice(2), 'base64url');
    return JSON.parse(String(code[1] === 'd' ? inflateRawSync(bytes) : bytes)) as unknown[];
  };
  assert.equal(slots(code).length, 17);
  assert.ok(slots(await encodeShare(populated)).length <= 15, 'no ignores: the trailing slots are omitted');
  const literal = (version: string, slots: unknown[]) => `${version}j` + Buffer.from(JSON.stringify(slots)).toString('base64url');
  assert.deepEqual((await decodeShare(literal('4', [...Array(15).fill(null), [30028]]))).run.ignoredIds, [30028]);
  assert.deepEqual((await decodeShare(literal('4', [...Array(15).fill(null)]))).run.ignoredIds, []);
  assert.deepEqual((await decodeShare(literal('3', [...Array(15).fill(null)]))).run.ignoredIds, []);
  await assert.rejects(decodeShare(literal('3', [...Array(15).fill(null), [30028]])), ShareCodeError, 'format 3 has no slot 15');
  assert.equal((await decodeShare(literal('4', [...Array(16).fill(null), 1]))).run.borrowIgnored, true);
  await assert.rejects(decodeShare(literal('4', [...Array(16).fill(null), 2])), ShareCodeError, 'the flag is 0 or 1');
  await assert.rejects(decodeShare(literal('4', [...Array(17).fill(null), 1])), ShareCodeError, 'format 4 ends at slot 16');
  for (const ignored of [[0], [1.5], [30028, 30028], ['30028'], {}]) await assert.rejects(decodeShare(literal('4', [...Array(15).fill(null), ignored])), ShareCodeError);
  await assert.rejects(decodeShare(literal('4', [...Array(8).fill(null), [30028], ...Array(6).fill(null), [30028]])), ShareCodeError, 'a card cannot be pinned and ignored');
  const local = defaultState(data);
  local.run.ignoredIds = [30001];
  applySharedChoices(local, await decodeShare('3jW10'));
  assert.deepEqual(local.run.ignoredIds, [], 'an older link replaces the ignored cards like every other choice');
  assert.equal(local.run.borrowIgnored, false);
});

test('format 5 stores the stars on each of the six umas; older formats place per-side totals the way the form does', async () => {
  const literal = (version: string, slots: unknown[]) => `${version}j` + Buffer.from(JSON.stringify(slots)).toString('base64url');
  const choices = structuredClone(populated);
  choices.run.targetLineage = { 201601: [0, 2, 0, 0, 0, 1] };
  const code = await encodeShare(choices);
  assert.equal(code[0], '5');
  assert.deepEqual(await decodeShare(code), choices, 'a grandparent-only lineage survives the round trip');
  assert.deepEqual((await decodeShare(literal('4', [null, null, null, null, [[201601, 2, 1, 5, 3]]]))).run.targetLineage, { 201601: [3, 2, 0, 3, 0, 0] });
  assert.deepEqual((await decodeShare(literal('2', [null, null, null, null, [[201601, 2, 0, 0, 0]]]))).run.targetLineage, { 201601: [1, 1, 0, 0, 0, 0] }, 'an unentered total gives each copy one star');
  assert.deepEqual((await decodeShare(literal('5', [null, null, null, null, [[201601, 0, 0, 0, 0, 0, 0]]]))).run.targetLineage, { 201601: [0, 0, 0, 0, 0, 0] });
  await assert.rejects(decodeShare(literal('5', [null, null, null, null, [[201601, 2, 1, 5, 3]]])), ShareCodeError, 'format 5 has no per-side tuples');
  await assert.rejects(decodeShare(literal('4', [null, null, null, null, [[201601, 0, 2, 0, 0, 0, 1]]])), ShareCodeError, 'format 4 has no per-uma tuples');
  for (const bad of [[201601, 0, 2, 0, 0, 0, 4], [201601, 0, 2, 0, 0, 0, -1], [201601, 0, 2, 0, 0, 0, 1.5], [201601, 0, 2, 0, 0, 0, '1']]) {
    await assert.rejects(decodeShare(literal('5', [null, null, null, null, [bad]])), ShareCodeError, JSON.stringify(bad));
  }
});

test('schedule overrides reject ambiguous IDs and invalid flags', async () => {
  for (const overrides of [[0], [1.5], [623, -623], ['623'], [Number.MAX_SAFE_INTEGER + 1], {}]) {
    const code = '3j' + Buffer.from(JSON.stringify([...Array(14).fill(null), overrides])).toString('base64url');
    await assert.rejects(decodeShare(code), ShareCodeError);
  }
  for (const overrides of [{ '0623': true }, { invalid: false }, { 623: 1 }]) {
    const choices = structuredClone(populated);
    choices.run.raceOverrides = overrides as unknown as Record<string, boolean>;
    await assert.rejects(encodeShare(choices), ShareCodeError);
  }
});
