// Every user-facing sentence the panels show outside their data, in one place so tone and terminology can be
// reviewed together. Pure strings and string functions: nothing here touches lit or the DOM.
import { BLUE_SPARK_INSPIRATION_RANGE_BY_STARS, BLUE_SPARK_START_UNCAP_BY_STARS, BORROWED_SLOTS, DECK_SIZE, PRIORITIZED_SKILLS_MAX, STARS_PER_SPARK_MAX, UMAS_PER_PARENT_SIDE } from '../model/rules.ts';
import { BLUE_STAR_BANDS } from '../model/stats.ts';

const OWNED_SLOTS = DECK_SIZE - BORROWED_SLOTS;

export const COPY = {
  share: {
    title: 'Share run',
    controls: 'Copy or load choices',
    description: "The address bar follows panels 1–4 and your prioritized skill order and exclusions. Copy its URL to share or bookmark your choices. Loading replaces those choices. Inventory, advanced settings and agenda picks stay on this device, so results can differ.",
    code: 'Reusable code',
    link: 'Shareable URL',
    copyCode: 'Copy code',
    copyLink: 'Copy URL',
    input: 'Paste a code or URL to load',
    load: 'Load choices',
    updating: 'Updating the share code…',
    ready: (length: number) => `${length} characters. The code updates after you edit your choices.`,
    copied: 'Copied.',
    generateFailed: 'Could not update the share code. Your choices are saved on this device. Try an up-to-date browser.',
    loadFailed: 'This code is invalid or incomplete. Your saved choices were kept.',
    saveFailed: 'Choices loaded, but this browser could not save them. Copy the share code before leaving this page.',
    unsupported: 'This code uses a newer or unsupported share format. Try updating the app. Your saved choices were kept.',
    tooLarge: 'These choices exceed the share-code size limit. Your saved choices were kept.',
    editedDuringLoad: 'Your choices changed while the code was loading. Load it again to replace them.',
    copyManually: "After closing this message, use your browser's Copy command on the selected text.",
    unavailable: 'Some saved choices are unavailable in this game data. Their IDs are kept in your save and share code, but excluded from calculations. Estimates cover only the available choices.',
    missingTrainee: (id: number) => `Unavailable trainee: ${id}`,
    missingCards: (ids: number[]) => `Unavailable pinned cards: ${ids.join(', ')}`,
    missingSkills: (ids: number[]) => `Unavailable skills: ${ids.join(', ')}`,
  },
  app: {
    tagline: 'Independent-training deck builder for white-spark farming',
    resetAll: 'Reset all',
    resetAllTip: 'Start over: clears every choice except your inventory and advanced settings',
    resetAllConfirm: 'Reset all? This clears the trainee, parent goal, targets, legacy screen, pinned cards, agenda picks, prioritized order, training focus and win threshold. Your inventory and advanced settings are kept.',
    waiting: 'Start with step 1: pick the uma you will train. The deck, estimate and agenda fill in from there. Your card inventory can be set in Card ranking at any time.',
    searching: 'Searching for a better deck. The estimates below already reflect your inputs for the deck shown.',
    searchFailed: "Deck search could not finish. The displayed deck's estimates match your current inputs.",
    retrySearch: 'Retry search',
  },
  trainee: {
    title: 'Trainee',
    tip: 'The uma you will train. Her own support cards leave the deck, her innate and awakening skills count as covered, and her growth rates and aptitudes feed the stat and race models.',
    starsTip: "Her rarity after the pieces you have used on her. Sets the base stats and the unique skill's starting level.",
    savedStars: (rarity: number) => `Your saved star count is kept. Estimates use this trainee's current minimum of ${rarity} stars.`,
    placeholder: 'Search uma name or outfit…',
    empty: 'Pick the uma you will train.',
    change: 'Change',
    interpolated: (stars: number) => `GameTora lists no ${stars}★ table for her, so these sit between the nearest listed star counts.`,
  },
  goal: {
    title: 'Parent goal',
    tip: 'What one finished parent must carry: a blue spark on an accepted stat, a pink spark on an accepted aptitude, and every required white spark, all at their minimum stars.',
    blueLegend: 'Required blue spark',
    pinkLegend: 'Required pink spark',
    pinkAlternatives: 'Any one of these results satisfies the pink requirement.',
    anyStat: 'Any stat',
    addPink: 'Add spark',
    minimumStars: 'Minimum stars',
  },
  templates: {
    summary: 'Load a template',
    tip: 'Generic starting points for parents at three effort levels. Lite is a usable parent for little effort, decent is a solid parent for moderate effort, and godly stacks on everything possible.',
    confirm: (name: string) => `Load "${name}"? This replaces your current goal requirements and target list.`,
    lineageKept: 'Existing entries are kept.',
  },
  targets: {
    legend: 'Target white sparks',
    tip: 'The white skills you want the finished parent to carry as sparks. A card that gives the skill or its gold form counts as a source. Select a chip to edit its goal and lineage, and select it again to close.',
    placeholder: 'Search a skill to add…',
    required: 'Required',
    preferred: 'Preferred',
    none: 'No targets yet. Search a skill above or load a template.',
    noWhite: 'No white spark',
    unsupported: 'This skill has no released white spark. Its target and saved lineage are kept for review. Its spark chance is zero, and the lineage gives no hints.',
    goalsHeading: 'Goals for target white spark',
    lineageHeading: 'White sparks in lineage',
    priorityTip: 'Lower numbers give more weight: priority 0 = 1, priority 1 = 0.5, priority 2 = 0.25. Preferred white sparks count at any star level. Several lower-weight sparks can outweigh one higher-weight spark. This does not change the prioritized-skills list.',
    lineageTip: (multiplier: number) => `Copies of this white spark already in the lineage, per parent side: how many of the three umas on that side (the parent and her two grandparents) carry it, and their star total. Each copy rolls for the hint at both inspiration events, and each copy multiplies the spark chance by ×${multiplier}.`,
    fromTrainee: 'from trainee',
  },
  legacy: {
    title: 'Legacy',
    tip: 'Copy the game\'s legacy screen, shown before the run starts: the "+XX" each parent adds above every stat, and the aptitudes after inheritance. "By stars" enters the blue spark of each uma instead, for a parent found on a database.',
    byStars: 'By stars',
    byStarsTip: "Enter each uma's blue spark by stars instead of the +XX",
    reset: 'Reset',
    resetTip: "Clear every gain to +0 and restore the trainee's own aptitudes",
    pinkSparks: 'Pink sparks',
    pinkSparksTip: 'Enter parent and grandparent pink sparks for mid-run aptitude estimates',
    resetPink: 'Reset pink sparks',
    resetPinkTip: "Clear pink sparks and restore the trainee's base aptitudes",
    gainsLabel: 'start gain per stat',
    gainsTip: `The "+XX" above each stat on the legacy screen, per parent. Each value decodes to the blue sparks behind it. One parent side has ${UMAS_PER_PARENT_SIDE} umas (the parent and her two grandparents) with one blue spark each. Dimmed choices need sparks already assigned to other stats; selecting one takes those sparks, fewest stars first.`,
    sparksTip: `Each parent and her two grandparents carry one blue spark: a stat and 1 to ${STARS_PER_SPARK_MAX} stars, as a database lists them. A slot shows — after its stat was set to +0 above; pick her stat to fill it.`,
    laterTip: `Expected extra stat from the two inspiration events. A 3★ spark procs at 90%, 2★ at 80%, 1★ at 70%, times (1 + affinity/100). Each proc rolls 1 to ${BLUE_SPARK_INSPIRATION_RANGE_BY_STARS[1]![1]} for 1★, 1 to ${BLUE_SPARK_INSPIRATION_RANGE_BY_STARS[2]![1]} for 2★, 1 to ${BLUE_SPARK_INSPIRATION_RANGE_BY_STARS[3]![1]} for 3★; the assumed mean per star is an advanced setting. Each spark also raises the stat's starting cap by +${BLUE_SPARK_START_UNCAP_BY_STARS[1]} / +${BLUE_SPARK_START_UNCAP_BY_STARS[2]} / +${BLUE_SPARK_START_UNCAP_BY_STARS[3]} by stars.`,
    aptTip: "Copy all grades from the legacy screen after selecting both parents. Raising a grade above the trainee's base estimates the minimum pink stars behind it.",
    pinkHeading: 'Pink sparks in the six-uma lineage',
    pinkTip: 'Enter the pink sparks you know. Empty slots count as zero sparks. Pick an aptitude to start at 3★, or clear it to return to zero. Estimated entries come from the grades you set and can be edited. Dimmed aptitude choices reassign other sparks to make room.',
    planningOverride: 'Some grades are planning overrides outside starting inheritance. They still control the agenda. Pink sparks remain unchanged.',
    aboutTitle: 'How grades and pink sparks relate',
    about: [
      'The agenda uses the starting surface and distance grades. These grades already include starting increases from parent sparks.',
      "Raising a grade above the trainee's base estimates the minimum pink stars behind it. Grades outside the starting-inheritance range are planning overrides and keep the pink lineage unchanged.",
      'Dimmed grade choices need slots used by other pink sparks. Selecting one reassigns the weakest other sparks and adjusts the affected aptitudes, never below their base.',
      'Parent goals use the pink sparks to estimate mid-run increases. Unknown below-B eligibility produces a probability range. S is reached only during a career.',
    ],
    pickTrainee: 'Pick a trainee first.',
  },
  run: {
    title: 'Run',
    scenario: 'Scenario',
    focus: 'Training focus',
    focusTip: 'The training focus you will set in independent training. It shifts how the run splits its stat gains.',
    threshold: 'Race win chance at least',
    thresholdTip: 'A G1 is scheduled automatically when its win chance is at least this. Lower it for more races and more fans; raise it for fewer expected losses.',
    pins: 'Pinned cards',
    pinsTip: `Cards the deck must include. An owned pin takes one of the ${OWNED_SLOTS} owned slots; a pin you do not own is borrowed at LB4 and takes the friend's slot.`,
    pinPlaceholder: 'Search a support card to pin…',
    noPins: 'Nothing pinned. Our Grand Concert needs a Light Hello card, so pin one.',
    borrowTip: "Not in your inventory, so it takes the friend's slot at LB4.",
    tooManyPins: (n: number) => `${n} owned cards pinned: the ${OWNED_SLOTS} with the best added spark chance stay.`,
    borrowFromAll: 'Borrow the best card overall, not the best leftover pin',
    noLightHello: 'No Light Hello card is marked owned. Our Grand Concert needs one.',
  },
  settings: {
    title: 'Inventory & settings',
    inventory: 'Inventory',
    inventoryTip: 'Every card counts as owned at LB4 until you change it in the card ranking. Export saves those changes to a file; import loads one.',
    export: 'Export',
    import: 'Import',
    reset: 'Reset',
    resetInventoryConfirm: 'Forget every card adjustment and count every card as owned at the default limit break?',
    importFailed: (reason: string) => `Import failed: ${reason}`,
    advanced: 'Advanced settings',
    advancedTip: 'Rates and scales the model needs that the game does not publish. Each field shows its default; changed values are marked.',
    resetAdvanced: 'Reset advanced settings',
    defaultLabel: 'default',
  },
  deck: {
    title: 'Suggested deck',
    tip: 'Five owned cards and one borrowed card. Search favors completing every required spark, then preferred sparks on successful parents within the advanced tie tolerance. This is the best deck found under the estimates, not a guaranteed global optimum.',
    noCards: 'No owned cards. Mark the cards you own in the card ranking.',
    steps: 'How the deck was built',
    borrowed: "LB4 (friend's)",
  },
  estimate: {
    title: 'Parent goal estimate',
    incomplete: 'Complete the goal inputs for a combined estimate.',
    headline: 'Chance per final spark roll that the parent gets every required spark',
    attemptsTip: 'Attempts count final spark rolls, including rerolls. The estimate treats them as independent with the same odds.',
    editPink: 'Edit pink sparks in Legacy',
    preferred: 'Preferred white sparks',
    preferredNote: 'These individual chances do not require the rest of the goal to succeed.',
    assumptions: 'Assumptions and aptitude eligibility',
    assumptionsNote: 'Stats share the same outcome with rank. Hint pickups and unlinked events are treated as independent. The agenda keeps its starting aptitude estimates.',
  },
  priorities: {
    title: 'Prioritized skills',
    tip: `Enter these in independent training's prioritized skills list, in this order. Only these ${PRIORITIZED_SKILLS_MAX} steer the run's event choices. Required targets come first, then preferred and other skills; drag a row or use the arrows to reorder within each group. Excluded choices are not counted as available sources.`,
    export: 'Export list',
    reset: 'Reset',
    empty: 'Nothing to prioritize yet.',
    notListed: 'Not listed:',
    removed: 'Removed:',
    conflicts: 'Choice conflicts',
    conflictsTip: 'These events offer more than one wanted skill, and the run can pick only one option per event. The option whose skill sits higher in the prioritized list wins. That the list order settles a contested option is an assumption: the game confirms prioritized skills steer choices, not how ties between them resolve.',
    kinds: {
      target: { label: 'target', tip: 'Leads to a target and needs the run to pick this option at an event.' },
      other: { label: 'not a target', tip: 'Not a target, but listing it steers the run to this option and its skill.' },
      given: { label: 'target, no choice', tip: 'A target the run gets without choosing anything. It is listed to fill the slot; the order does not matter for it.' },
    },
  },
  prediction: {
    title: 'Predicted run',
    tip: `Means with the run-to-run spread (±1 sd) from an empirical fit of logged independent-training runs. ≥${BLUE_STAR_BANDS.mid} and ≥${BLUE_STAR_BANDS.high} are the chances of the stat reaching the 2★ and 3★ blue spark bands.`,
    ssTip: "Chance the final rank is SS or above, which improves white spark star odds. An estimate: the rank score is the game's stat table plus estimated skill terms, and its spread comes from the fitted stat model.",
    breakdown: 'Where the stats come from',
  },
  coverage: {
    title: 'Target coverage',
    tip: "Chance the run hands over each target's hint, by form. The spark chance assumes you buy the best hinted form at the end: gold at 40%, otherwise a released ◎ upgrade at 25%, otherwise the base skill at 20%. Where a ◎ exists, buying it needs no separate hint. The run itself buys nothing.",
    noSource: 'no source in the deck',
    spCostTip: 'The base cost of every target bought once in its best hinted form, with prerequisites and no hint discounts. An upper bound to check against the estimated SP; you choose the purchases at the end of the run.',
  },
  agenda: {
    title: 'G1 agenda',
    tip: 'Career goal races are fixed and shown in gold. Every other G1 the trainee can win at or above the threshold in Run is scheduled once. Pick a race by hand to override the rule.',
    open: 'Show the race grid',
    reset: 'Reset',
    resetTip: 'Return every slot to the automatic rule',
    manualTip: 'Picked by hand. Reset returns this slot to the automatic rule.',
    skip: '— skip —',
    careerGoal: 'career goal',
    streakTip: (n: number) => `${n} races in consecutive half-month slots: the streak penalty applies`,
    fansTip: (bonus: number) => `Race rewards include the selected deck's ${bonus}% Fan Bonus and estimated non-win placings. Finale rewards assume completion and do not add to the calendar race count or earlier fan checks. Concert rewards use manual JP measurements and the Scenario settings. Random race reward increases are omitted, so the estimate can remain low.`,
    aboutTitle: 'How races are scheduled',
    about: [
      'Career goal races are fixed. Every other G1 the trainee can win at or above the threshold is scheduled once, in the year that costs fewer expected losses. When two G1s share a slot, the one more umas can run comfortably wins the tie, a stand-in for how common the race is on parents.',
      "Win chances follow Shoppo_ura's independent-training data: 110% at A/A minus a penalty per surface grade (B −10, C −20, D −30, E −50, F −60, G −90) and per distance grade (B −10, C −20, D −30, E −40, F −60, G −90), minus the streak penalty for consecutive races (3rd in a row −5, 4th −20, 5th −30, 6th and later −50), clamped to 0 to 100%.",
      'Stats, skills and mood do not matter. A career goal the run would end on losing is always won; a participation-only goal rolls the odds.',
    ],
  },
  ranking: {
    title: 'Card ranking',
    tip: 'Every Global support card scored against your targets. Set the limit break of the cards you own here (or mark them not owned); the deck and the predictions follow.',
    showUnowned: 'Show not owned',
    sortHint: 'click a header to sort',
    targetTip: 'Sorted by the sum of Required target chances, then priority-weighted Preferred target chances, then Total stat gain. Each percentage is this card\'s own chance at rank SS. See "How cards are scored" below.',
    basisTip: 'Where the stat numbers come from. "Observed" means the Loopacord logs have this card at this limit break, "observed at another LB" shifts a logged limit break by the model, and "model" is the fitted formula from the card passives.',
    traineeCard: "trainee's card",
    aboutTitle: 'How cards are scored',
    about: [
      'Each percentage uses this card\'s own skill sources and assumes rank SS for star quality. Required sparks use your minimum stars; Preferred sparks count at any star level. Their ranking weights halve with each priority step; individual percentages are unweighted.',
      'Current skill priorities and lineage generation bonuses apply. Trainee, scenario, inherited hints and other cards are excluded. These are individual chances, not the improvement from replacing a card or the chance of completing your parent goal.',
    ],
  },
  fields: {
    notOwned: 'not owned',
    default: '(default)',
  },
} as const;
