// Every user-facing sentence the panels show outside their data, in one place so tone and terminology can be
// reviewed together. Pure strings and string functions: nothing here touches lit or the DOM.
import { BLUE_SPARK_INSPIRATION_RANGE_BY_STARS, BLUE_SPARK_START_UNCAP_BY_STARS, BORROWED_SLOTS, DECK_SIZE, PRIORITIZED_SKILLS_MAX, STARS_PER_SPARK_MAX, UMAS_PER_PARENT_SIDE } from '../model/rules.ts';
import { BLUE_STAR_BANDS } from '../model/stats.ts';

const OWNED_SLOTS = DECK_SIZE - BORROWED_SLOTS;

// Panel titles and control labels that other sentences name. Each is defined once here and used both on the control
// and in those sentences, so renaming a control updates every instruction that points to it.
const TITLE = {
  details: 'Prediction details', goal: 'Parent goal', legacy: 'Legacy', run: 'Run', deck: 'Suggested deck',
  coverage: 'Target coverage', ranking: 'Card ranking',
} as const;
const LABEL = {
  resetAll: 'Reset all', perParent: 'Per parent', blueByStars: 'Blue per parent', scenario: 'Scenario',
  exportFile: 'Export to file', importFile: 'Import from file', agendaReset: 'Reset',
  observedOmitted: 'Not separately modelled', scoringAbout: 'How cards are scored',
} as const;

export const COPY = {
  share: {
    generateFailed: 'Could not update the share code. Your choices are saved on this device. Try an up-to-date browser.',
    loadFailed: 'This code is invalid or incomplete. Your saved choices were kept.',
    saveFailed: 'Choices loaded, but this browser could not save them. Copy the URL before leaving this page.',
    unsupported: 'This code uses a newer or unsupported share format. Try updating the app. Your saved choices were kept.',
    tooLarge: 'These choices exceed the share-code size limit. Your saved choices were kept.',
    editedDuringLoad: 'Your choices changed while the code was loading. Load it again to replace them.',
    unavailable: 'Some saved choices are unavailable in this game data. Their IDs are kept in your save and share code, but excluded from calculations. Estimates cover only the available choices.',
    missingTrainee: (id: number) => `Unavailable trainee: ${id}`,
    missingCards: (ids: number[]) => `Unavailable pinned cards: ${ids.join(', ')}`,
    missingSkills: (ids: number[]) => `Unavailable skills: ${ids.join(', ')}`,
  },
  app: {
    tagline: 'Independent-training deck builder for white-spark farming',
    resetAll: LABEL.resetAll,
    resetAllTip: 'Start over: clears every choice except your inventory and advanced settings',
    resetAllConfirm: `${LABEL.resetAll}? This clears the trainee, parent goal, targets, legacy screen, pinned and ignored cards, agenda picks, prioritized order, training focus and win threshold. Your inventory and advanced settings are kept.`,
    waiting: `Start with step 1: pick the uma you will train. The deck, estimate and agenda fill in from there. Your card inventory can be set in ${TITLE.ranking} at any time.`,
    searching: 'Searching for a better deck. The estimates below already reflect your inputs for the deck shown.',
    searchFailed: "Deck search could not finish. The displayed deck's estimates match your current inputs.",
    retrySearch: 'Retry search',
    hideInputs: '« Hide inputs',
    hideInputsTip: 'Give the results the full width. The summary line keeps the run in view.',
    showInputs: '» Show inputs',
  },
  summary: {
    blue: 'Blue',
    pink: 'Pink',
    required: 'Required',
    preferred: 'Preferred',
  },
  warnings: {
    title: 'Warnings',
    tip: 'Anything that limits or changes the estimates below: missing inputs, an impossible goal, a deck the search could not complete, and events where two wanted skills compete for one option.',
    conflicts: 'Choice conflicts',
    conflictsTip: 'These events offer more than one wanted skill, and the run can pick only one option per event. The option of the target listed higher wins: required before preferred, preferred by their priority, and between required targets whichever order gives the best chance of every required spark. That the list order settles a contested option is an assumption: the game confirms prioritized skills steer choices, not how ties between them resolve.',
    conflictsNote: `The run takes one option per event and the target listed higher takes it. To change which one, change the priorities or the targets in ${TITLE.goal}.`,
  },
  details: {
    title: TITLE.details,
    tip: 'For checking the tool\'s work. Each number above is broken into the parts it came from, and each section ends with how it is computed. The stat sources and target coverage need a complete deck.',
    sections: (complete: boolean) => (complete ? ['goal estimate', 'stat sources', 'target coverage', 'deck search'] : ['goal estimate', 'deck search']).join(' · '),
    incomplete: 'Stat sources and target coverage appear once the deck is complete.',
    explore: 'Explore how each number above was reached',
    estimate: 'Goal estimate breakdown',
    estimateTip: 'Each required spark on its own. The combined chance above needs all of them in one run.',
    aboutGoal: 'How the goal estimate is computed',
    aboutStats: 'How the stats are estimated',
  },
  trainee: {
    title: 'Trainee',
    tip: 'The uma you will train. Her own support cards leave the deck, her innate and awakening skills count as covered, and her growth rates and aptitudes feed the stat and race models.',
    starsTip: "Her rarity after the pieces you have used on her. Sets the base stats and the unique skill's starting level.",
    savedStars: (rarity: number) => `Your saved star count is kept. Estimates use this trainee's current minimum of ${rarity} stars.`,
    placeholder: 'Search uma name or outfit…',
    empty: 'Pick the uma you will train.',
    change: 'Change',
    interpolated: (stars: number) => `GameTora lists no ${stars}★ table for her, so these sit between the nearest listed star counts.`,
  },
  goal: {
    title: TITLE.goal,
    tip: 'What one finished parent must carry: a blue spark on an accepted stat, a pink spark on an accepted aptitude, and every required white spark, all at their minimum stars.',
    blueLegend: 'Required blue spark',
    pinkLegend: 'Required pink spark',
    pinkAlternatives: 'Any one of these results satisfies the pink requirement.',
    anyStat: 'Any stat',
    addPink: 'Add spark',
    minimumStars: 'Minimum stars',
  },
  templates: {
    summary: 'Load a template',
    tip: 'Generic starting points for parents at three effort levels. Lite is a usable parent for little effort, decent is a solid parent for moderate effort, and godly stacks on everything possible.',
    confirm: (name: string) => `Load "${name}"? This replaces your current goal requirements and target list.`,
    lineageKept: 'Existing entries are kept.',
  },
  targets: {
    legend: 'Target white sparks',
    tip: 'The white skills you want the finished parent to carry as sparks. A card that gives the skill or its gold form counts as a source. Each group adds through its own search. Select a name to edit its goal and lineage, and select it again to close. Closing a group also closes its editor.',
    placeholder: { required: 'Add a required skill…', preferred: 'Add a preferred skill…' },
    roles: { required: 'Required', preferred: 'Preferred' },
    none: 'No targets yet. Search a skill above or load a template.',
    noWhite: 'No white spark',
    unsupported: 'This skill has no released white spark. Its target and saved lineage are kept for review. Its spark chance is zero, and the lineage gives no hints.',
    goalsHeading: 'Goals for target white spark',
    lineageHeading: 'White sparks in lineage',
    priorityTip: 'Lower numbers give more weight: priority 0 = 1, priority 1 = 0.5, priority 2 = 0.25. Preferred white sparks count at any star level. Several lower-weight sparks can outweigh one higher-weight spark. This does not change the prioritized-skills list.',
    lineageTip: (multiplier: number) => `Copies of this white spark already in the lineage: how many of the six umas (each parent and her two grandparents) carry it, and their star total. Each copy rolls for the hint at both inspiration events, and each copy multiplies the spark chance by ×${multiplier}. Totals fill the parents first, then the grandparents; "${LABEL.perParent}" sets each uma instead.`,
    lineageCopies: 'Copies',
    lineageStars: 'Total stars',
    lineageSummary: (copies: number, stars: number) => `${copies} ${copies === 1 ? 'copy' : 'copies'} · ${stars}★ total`,
    perParent: LABEL.perParent,
    perParentTip: 'Enter the stars on each parent and grandparent instead of the totals',
    fromTrainee: 'from trainee',
    remove: 'Remove',
  },
  legacy: {
    title: TITLE.legacy,
    tip: `Copy the game's legacy screen, shown before the run starts: the "+XX" each parent adds above every stat, and the aptitudes after inheritance. "${LABEL.blueByStars}" enters the blue spark of each uma instead, for a parent found on a database.`,
    byStars: LABEL.blueByStars,
    byStarsTip: 'Enter the blue spark of each parent and grandparent instead of the +XX',
    reset: 'Reset',
    resetTip: "Clear every gain to +0 and restore the trainee's own aptitudes",
    pinkSparks: 'Pink per parent',
    pinkSparksTip: 'Enter the pink spark of each parent and grandparent for mid-run aptitude estimates',
    resetPink: 'Reset',
    resetPinkTip: "Clear pink sparks and restore the trainee's base aptitudes",
    gainsLabel: 'start gain per stat',
    gainsTip: `The "+XX" above each stat on the legacy screen, per parent. Each value decodes to the blue sparks behind it. One parent side has ${UMAS_PER_PARENT_SIDE} umas (the parent and her two grandparents) with one blue spark each. Dimmed choices need sparks already assigned to other stats; selecting one takes those sparks, fewest stars first.`,
    sparksTip: `Each parent and her two grandparents carry one blue spark: a stat and 1 to ${STARS_PER_SPARK_MAX} stars, as a database lists them. A slot shows — after its stat was set to +0 above; pick her stat to fill it.`,
    laterTip: `Expected extra stat from the two inspiration events. A 3★ spark procs at 90%, 2★ at 80%, 1★ at 70%, times (1 + affinity/100). Each proc rolls 1 to ${BLUE_SPARK_INSPIRATION_RANGE_BY_STARS[1]![1]} for 1★, 1 to ${BLUE_SPARK_INSPIRATION_RANGE_BY_STARS[2]![1]} for 2★, 1 to ${BLUE_SPARK_INSPIRATION_RANGE_BY_STARS[3]![1]} for 3★; the assumed mean per star is an advanced setting. Each spark also raises the stat's starting cap by +${BLUE_SPARK_START_UNCAP_BY_STARS[1]} / +${BLUE_SPARK_START_UNCAP_BY_STARS[2]} / +${BLUE_SPARK_START_UNCAP_BY_STARS[3]} by stars.`,
    aptTip: "Copy all grades from the legacy screen after selecting both parents. Raising a grade above the trainee's base estimates the minimum pink stars behind it.",
    planningOverride: 'Some grades are planning overrides outside starting inheritance. They still control the agenda. Pink sparks remain unchanged.',
    aboutTitle: 'How grades and pink sparks relate',
    about: [
      'The agenda uses the starting surface and distance grades. These grades already include starting increases from parent sparks.',
      "Raising a grade above the trainee's base estimates the minimum pink stars behind it. Grades outside the starting-inheritance range are planning overrides and keep the pink lineage unchanged.",
      'Dimmed grade choices need slots used by other pink sparks. Selecting one reassigns the weakest other sparks and adjusts the affected aptitudes, never below their base.',
      'Parent goals use the pink sparks to estimate mid-run increases. Unknown below-B eligibility produces a probability range. S is reached only during a career.',
    ],
    pickTrainee: 'Pick a trainee first.',
  },
  run: {
    title: TITLE.run,
    scenario: LABEL.scenario,
    focus: 'Training focus',
    focusTip: 'The training focus you will set in independent training. It shifts how the run splits its stat gains.',
    threshold: 'Race win chance at least',
    thresholdTip: 'A G1 is scheduled automatically when its win chance is at least this. Lower it for more races and more fans; raise it for fewer expected losses.',
    pins: 'Pinned cards',
    pinsTip: `Cards the deck must include. An owned pin takes one of the ${OWNED_SLOTS} owned slots; a pin you do not own is borrowed at LB4 and takes the friend's slot.`,
    pinPlaceholder: 'Search a support card to pin…',
    noPins: 'Nothing pinned. Our Grand Concert needs a Light Hello card, so pin one.',
    borrowTip: "Not in your inventory, so it takes the friend's slot at LB4.",
    tooManyPins: (n: number) => `${n} owned cards pinned: the ${OWNED_SLOTS} with the best added spark chance stay.`,
    borrowFromAll: 'Borrow the best card overall, not the best leftover pin',
    noLightHello: 'No Light Hello card is marked owned. Our Grand Concert needs one.',
    ignored: 'Ignored cards',
    ignoredTip: `Cards this run never suggests for an owned slot, nor for the friend's slot unless allowed below. Ignore a card here or with the button beside it in ${TITLE.deck} or ${TITLE.ranking}.`,
    ignorePlaceholder: 'Search a support card to ignore…',
    noIgnored: 'Nothing ignored.',
    borrowIgnored: "Allow ignored cards in the friend borrow slot",
  },
  cards: {
    pin: (name: string) => `Pin ${name}`,
    unpin: (name: string) => `Unpin ${name}`,
    ignore: (name: string) => `Ignore ${name}`,
    unignore: (name: string) => `Stop ignoring ${name}`,
  },
  settings: {
    title: 'Settings',
    inventoryTitle: 'Card inventory',
    scan: 'Import using screenshots',
    inventoryTip: `Every card counts as owned at LB4 until you change it in ${TITLE.ranking}. ${LABEL.exportFile} saves those changes; ${LABEL.importFile} loads them.`,
    export: LABEL.exportFile,
    import: LABEL.importFile,
    reset: 'Reset',
    resetInventoryConfirm: 'Forget every card adjustment and count every card as owned at the default limit break?',
    importFailed: (reason: string) => `Import failed: ${reason}`,
    advanced: 'Advanced settings',
    advancedTip: 'Rates and scales the model needs that the game does not publish. Each field shows its default; changed values are marked.',
    exportSettings: 'Export settings',
    resetAdvanced: 'Reset advanced settings',
    defaultLabel: 'default',
  },
  deck: {
    title: TITLE.deck,
    tip: 'Five owned cards and one borrowed card, pins first. Search favors completing every required spark, then preferred sparks on successful parents within the advanced tie tolerance. This is the best deck found under the estimates, not a guaranteed global optimum. Each slot\'s buttons pin the card or ignore it for this run.',
    noCards: 'No owned cards. Mark the cards you own in the card ranking.',
    steps: 'How the deck was built',
    borrowed: "LB4 (friend's)",
  },
  modelCoverage: {
    observed: (lb: number) => `Observed · LB${lb}`,
    adjusted: (lb: number) => `Adjusted · from LB${lb}`,
    predicted: 'Model estimate',
    observedDetail: (lb: number, runs: number, source: string) => `Uses community results at LB${lb} from ${source === 'loopacord' ? 'at least ' : ''}${runs} logged runs (${source}).`,
    adjustedDetail: (from: number, to: number) => `Estimates LB${to} by applying the model's predicted difference between LB${from} and LB${to}.`,
    modelDetail: 'Estimated from this card\'s support effects. No qualifying recorded results are available for this card.',
    /** One tooltip line per coverage status: the effects the formula leaves out, each with the outcomes it affects. */
    coverageLine: (status: string, effects: string[]) => `${status}: ${effects.join(', ')}.`,
    effectEntry: (name: string, outcomes: string[], detail?: string) => `${name}${detail ? ` "${detail}"` : ''} (${outcomes.join(', ')})`,
    recordedDeck: 'Fixed at the recorded deck conditions',
    teamEffect: 'Team effect estimated from starting bond, not measured directly',
    observedEffects: `Recorded stats and SP can already include these effects as part of the card's combined contribution. "${LABEL.observedOmitted}" means the formula cannot isolate their contributions or adjust them individually.`,
    observedDeck: 'The recorded contribution stays fixed when deck-dependent effects change. No extra bonus is added on top of it.',
    statuses: { calculated: 'Calculated', approximated: 'Approximated', omitted: 'Not in formula', unrecognized: 'Not evaluated' },
    observedOmitted: LABEL.observedOmitted,
    affects: (outcomes: string[]) => `Affects ${outcomes.join(', ')}.`,
    limitations: (cards: number) => `Estimate limitations · ${cards} ${cards === 1 ? 'card' : 'cards'}`,
    limitationsDetail: `These notes describe limits of the formula. Recorded results can already include the effects listed here. Open a card's Basis detail in ${TITLE.ranking} for its source and full formula coverage.`,
    outcomes: { stats: 'stats', sp: 'SP', fans: 'fans', skills: 'skills', unknown: 'an outcome not yet evaluated' },
    reasons: {
      direct: 'Applied directly to its related estimate.',
      fitted: 'Included through a fitted relationship with recorded results.',
      hints: 'Used to estimate how often the card offers skill hints.',
      hintLevels: 'Hint levels do not change the current skill-cost estimate.',
      fanBonus: 'Added to the deck\'s Fan Bonus for the fan estimate.',
      bondShare: (share: number) => `Assumes the bond threshold is reached for ${share}% of the run.`,
      deckTypes: 'The formula checks the number of support types in the deck.',
      deckInitialStats: 'The formula counts support types in the deck to determine starting stats.',
      fans: 'Uses the agenda\'s estimated fans when available, otherwise the model\'s assumed active share.',
      friendshipCount: (share: number) => `Assumes the friendship-training threshold is reached for ${share}% of the run.`,
      totalBond: (share: number) => `Uses the model\'s total-bond assumption for ${share}% of the run.`,
      facilityLevel: (share: number) => `Assumes maximum facility level for ${share}% of the run.`,
      initialBond: 'The formula does not adjust these estimates for starting bond.',
      teamBond: 'Estimates the team bonus using the fitted starting-bond relationship. The team effect has not been measured directly.',
      raceBonus: 'The stat and SP reward baseline does not adjust for this deck\'s Race Bonus.',
      notFitted: 'This effect has no fitted contribution in the current formula.',
      notRetained: 'Tested as an extra input, but not selected for this estimate. That does not mean the effect has no impact.',
      insufficientData: 'There are too few suitable measurements to judge this effect for this estimate.',
      unsupported: 'This effect is recognized but is not included in the formula.',
      unknown: 'This effect has not been evaluated by the model.',
      unknownPayload: 'The imported effect contains parameters the model does not yet understand.',
      rewardFlag: 'Some skill rewards carry a source flag whose meaning has not been verified. Their probabilities are not adjusted for that flag.',
    },
  },
  estimate: {
    title: 'Parent goal estimate',
    tip: `The chance that one run's final spark roll gives every required spark, and how many runs that takes at three confidence levels. ${TITLE.details} below explains what limits it.`,
    incomplete: 'Complete the goal inputs for a combined estimate.',
    headline: 'Chance per final spark roll that the parent gets every required spark',
    attemptsTip: 'Attempts count final spark rolls, including rerolls. The estimate treats them as independent with the same odds.',
    editPink: `Edit pink sparks in ${TITLE.legacy}`,
    preferred: 'Preferred white sparks',
    preferredNote: 'These individual chances do not require the rest of the goal to succeed.',
    assumptions: 'Assumptions and aptitude eligibility',
    assumptionsNote: 'Stats share the same outcome with rank. Hint pickups and unlinked events are treated as independent. The agenda keeps its starting aptitude estimates.',
  },
  priorities: {
    title: 'Prioritized skills',
    tip: `Enter these in independent training's prioritized skills list, in this order. Only these ${PRIORITIZED_SKILLS_MAX} steer the run's event choices; a target outside them is not credited with its event options. Targets follow ${TITLE.goal}: required first, then preferred by priority. The extras below them are yours to arrange; the deck search does not read that order. The run takes one option per event, so an option a higher entry already takes is not listed; the chips under that entry swap it in.`,
    reset: 'Reset',
    empty: 'Nothing to prioritize yet.',
    notListed: 'Not listed:',
    hiddenRow: 'Hidden:',
    source: 'Source',
    hintSource: (cards: string[]) => `Available as a hint on ${cards.length === 1 ? 'this card' : 'these cards'} in the deck: ${cards.join('; ')}.`,
    allCandidates: 'Show all candidates',
    fewerCandidates: 'Show fewer',
    targetsFixed: `Target skills cannot be removed from the prioritized skills list. Change targets and their order in ${TITLE.goal}.`,
    roles: {
      required: { label: 'required', tip: 'A required target of the parent goal.' },
      preferred: { label: 'preferred', tip: 'A preferred target of the parent goal.' },
      extra: { label: 'extra', tip: 'Not a target. Listing it steers the run to this event option and its skill; the run buys it if it gets it.' },
    },
    marks: {
      hintsOnly: { label: 'hints only', tip: 'The run gets this target without choosing anything at an event. It is listed so the run chases its hints; its position does not matter.' },
      lostEvent: { label: 'lost event', tip: `Another target listed higher takes every event option that gives this one, so it gets nothing from those events and keeps only its hints. To change that, raise its priority in ${TITLE.goal} or change the competing target there.` },
    },
    instead: 'or instead:',
    listedAt: (n: number) => `(currently #${n})`,
    hidden: (n: number) => `${n} taken option${n === 1 ? '' : 's'} not listed`,
    pending: 'updating with the deck search',
  },
  prediction: {
    title: 'Predicted run',
    tip: `Means with the run-to-run spread (±1 sd) from an empirical fit of logged independent-training runs. ≥${BLUE_STAR_BANDS.mid} and ≥${BLUE_STAR_BANDS.high} are the chances of the stat reaching the 2★ and 3★ blue spark bands.`,
    ssTip: "Chance the final rank is SS or above, which improves white spark star odds. An estimate: the rank score is the game's stat table plus estimated skill terms, and its spread comes from the fitted stat model.",
    breakdown: 'Where the stats come from',
    scaling: (focus: string, multipliers: string, scale: string, races: number, reference: number) => `Card stats and SP use a race scaling of ×${scale} for ${races} races against the model's ${reference}-race reference. Career rewards use a separate estimate based on 23-race and 28-race measurements. Both card and career stats include the ${focus} focus multiplier (${multipliers}); SP does not.`,
    skillCost: (cost: string, sp: string, overBudget: boolean, extras: string) => `Buying every target at full price costs ${cost} of ${sp} estimated SP${overBudget ? ', more than the run is expected to earn' : ''} (the worst case in ${TITLE.coverage}). The listed extras would add ${extras} SP; the run does not need them.`,
    purchases: (pointsPerSp: number, referenceRate: number, referenceSp: number, fallback: boolean, unknown: number) => `Rank assumes all estimated SP is spent, averaging ${pointsPerSp.toFixed(2)} rating points per SP. ${fallback ? 'No obtainable skill has a known positive price.' : 'Obtainable skills contribute when their full-price value beats the reference rate. Availability limits their contribution, and inefficient optional skills or upgrades can be skipped.'} About ${Math.round(referenceSp).toLocaleString()} SP uses a reference rate of ${referenceRate.toFixed(2)} points per SP, derived from released white skills and the trainee's aptitudes independently of the deck. This rate is a planning assumption, not calibrated spending data. Fractional expected purchases approximate availability; shared outcomes and actual purchase budgets can differ. The full-price cost of the targets is checked separately, using each family's highest obtainable form with prerequisites, and the listed extras are priced apart from it. Goal spark chances assume the target forms are bought even when their cost exceeds estimated SP. Hint discounts, Fast Learner and SP variation are not modeled. ${unknown ? `${unknown} skill forms lack a verified individual rating and use rarity estimates. ` : ''}The skill-score spread describes uncertainty in spending efficiency; it is not a calibrated success rate.`,
    evidence: (rmse: string, observations: number) => `The spread uses raw gains between logged runs, with a sample-variance correction and estimated inspiration variance. The full total is converted above 1,200 before caps and rating. Correlated stats and errors in the predicted mean are not measured by this spread. The card formula's fitting error is ${rmse} per stat over ${observations} observations; this is not an accuracy guarantee for new cards. Race scaling comes from the measured 23-race and 28-race schedules, and focus multipliers come from one measured deck.`,
    raceBonus: (bonus: number) => `Career rewards include race rewards measured with the reference deck's Race Bonus. The baseline does not adjust for this deck's ${bonus}% Race Bonus, so comparisons between decks may miss that difference.`,
    capped: 'A stat is clamped to the scenario cap plus the blue sparks\' start-of-run uncaps. Uncaps from inspiration events and green sparks are unknown and left out.',
  },
  coverage: {
    title: TITLE.coverage,
    tip: "Chance the run hands over each target's hint, by form. The spark chance assumes you buy the best hinted form at the end: gold at 40%, otherwise a released ◎ upgrade at 25%, otherwise the base skill at 20%. Where a ◎ exists, buying it needs no separate hint. The run itself buys nothing.",
    noSource: 'no source in the deck',
    spCostTip: 'The base cost of every target bought once in its best hinted form, with prerequisites and no hint discounts. An upper bound to check against the estimated SP; you choose the purchases at the end of the run.',
  },
  agenda: {
    title: 'G1 agenda',
    tip: `Career goal races are fixed and shown in gold. Every other G1 the trainee can win at or above the threshold in ${TITLE.run} is scheduled once. Pick a race by hand to override the rule.`,
    open: 'Show the race grid',
    reset: LABEL.agendaReset,
    resetTip: 'Return every slot to the automatic rule',
    manualTip: `Picked by hand. ${LABEL.agendaReset} returns this slot to the automatic rule.`,
    skip: '— skip —',
    careerGoal: 'career goal',
    streakTip: (n: number) => `${n} races in consecutive half-month slots: the streak penalty applies`,
    fansTip: (bonus: number) => `Race rewards include the selected deck's ${bonus}% Fan Bonus and estimated non-win placings. Finale rewards assume completion and do not add to the calendar race count or earlier fan checks. Concert rewards use manual JP measurements and the ${LABEL.scenario} settings. Random race reward increases are omitted, so the estimate can remain low.`,
    aboutTitle: 'How races are scheduled',
    about: [
      'Career goal races are fixed. Every other G1 the trainee can win at or above the threshold is scheduled once, in the year that costs fewer expected losses. When two G1s share a slot, the one more umas can run comfortably wins the tie, a stand-in for how common the race is on parents.',
      "Win chances follow Shoppo_ura's independent-training data: 110% at A/A minus a penalty per surface grade (B −10, C −20, D −30, E −50, F −60, G −90) and per distance grade (B −10, C −20, D −30, E −40, F −60, G −90), minus the streak penalty for consecutive races (3rd in a row −5, 4th −20, 5th −30, 6th and later −50), clamped to 0 to 100%.",
      'Stats, skills and mood do not matter. A career goal the run would end on losing is always won; a participation-only goal rolls the odds.',
    ],
  },
  ranking: {
    title: TITLE.ranking,
    tip: 'Every Global support card scored against your targets. Set the limit break of the cards you own here (or mark them not owned); the deck and the predictions follow. Pinned cards and the suggested deck stay on top whatever the sort; each row\'s buttons pin the card or ignore it for this run.',
    showUnowned: 'Show not owned',
    sortHint: 'pins and the suggested deck first, then click a header to sort',
    targetTip: `Sorted by the sum of Required target chances, then priority-weighted Preferred target chances, then Total stat gain. Each percentage is this card's own chance at rank SS. See "${LABEL.scoringAbout}" below.`,
    basisTip: (reference: number, selected: number) => `Where each card's stat and SP estimates come from: community results at the shown limit break, an observation adjusted from a nearby limit break, or the formula alone. Each label's info icon gives the source and the effects the formula leaves out. The model uses ${reference} races as its reference, then scales card stats and SP to your ${selected}-race schedule; the training focus adjusts stats only.`,
    traineeCard: "trainee's card",
    aboutTitle: LABEL.scoringAbout,
    about: [
      'Each percentage uses this card\'s own skill sources and assumes rank SS for star quality. Required sparks use your minimum stars; Preferred sparks count at any star level. Their ranking weights halve with each priority step; individual percentages are unweighted.',
      'Current skill priorities and lineage generation bonuses apply. Trainee, scenario, inherited hints and other cards are excluded. These are individual chances, not the improvement from replacing a card or the chance of completing your parent goal.',
      'Observed and adjusted stat estimates come from recorded runs, so they already include effects the formula cannot separate, and they stay fixed when deck-dependent effects change. Model estimates use only the effects the formula covers. The suggested deck\'s estimate limitations list what is left out for each deck card.',
    ],
  },
  fields: {
    notOwned: 'not owned',
    default: '(default)',
  },
} as const;

/** A limit break as the game's card list shows it. */
const lbBadge = (lb: number) => lb === 4 ? 'MLB' : `${lb}LB`;

export const SCANNER_COPY = {
  title: 'Import using screenshots',
  subtitle: 'Read support cards and limit breaks from screenshots, review the results, then download your inventory.',
  planner: '← Uma parent deck',
  openPlanner: 'Open Uma parent deck',
  privacy: 'Screenshots stay in this browser. No account, upload, or API key.',
  choose: 'Choose screenshots',
  drop: 'or drop them anywhere on this panel',
  guidance: 'Use full-width, five-column Support Card List screenshots. Include all your SR and SSR cards, with some overlap between screenshots. Keep each person’s inventory in a separate batch.',
  rare: 'R cards are ignored in screenshots and exported at 4LB (MLB).',
  rareEmbedded: 'R cards are ignored in screenshots and keep their current limit break in your inventory.',
  missing: 'SR and SSR cards missing from the reviewed results will be exported as not owned. Check coverage before downloading.',
  partial: 'Cropped or covered rows may be missed. Include them fully in another screenshot, or add the card manually.',
  // Built from the labels of the planner's own controls, so renaming them updates the instructions.
  import: `In Uma parent deck, choose ${COPY.settings.import} in the ${COPY.settings.inventoryTitle} panel and select the downloaded inventory.json.`,
  loading: 'Loading card artwork…',
  scanning: (name: string, done: number, total: number) => `Reading ${name}${total ? ` · ${done} / ${total} cards` : '…'}`,
  busyDrop: 'Still reading. Add more screenshots when this batch finishes, or stop reading first.',
  referencesFailed: 'Could not load the card artwork. Check the connection and try again.',
  scannerLoadFailed: 'Could not open screenshot import. Check your connection and try again. If it keeps failing, reload the page.',
  scannerFailed: (detail: string) => `Recognition stopped. Completed results are kept. Try adding the remaining screenshots again.${detail ? ` Details: ${detail}` : ''}`,
  /** A screenshot's caption, and the message listed for one that was not read. */
  sourceStatus: {
    queued: 'Waiting to be read',
    reading: 'Reading…',
    unreadable: 'Could not read this image. Use a PNG, JPEG, or WebP image and try again.',
    noCards: 'No complete card badges found. Use a full-width screenshot of the five-column support card list.',
    failed: 'Not read because recognition stopped. Add this screenshot again.',
    stopped: 'Not read because reading was stopped. Add this screenshot again.',
  },
  cancel: 'Stop reading',
  stopped: 'Stopped',
  newBatch: 'New inventory',
  newBatchConfirm: 'Start a new inventory? This clears the current screenshots and review results.',
  add: 'Add a card',
  filter: 'Filter cards',
  search: 'Filter by card or screenshot name',
  card: 'Card',
  lb: 'Limit break',
  unknownLb: 'Not read',
  lbOption: (lb: number) => lb === 4 ? '4 (MLB)' : String(lb),
  selectCard: 'Choose a card',
  searchCards: 'Search name, title, or type',
  noCardMatches: 'No cards match. Try another name or title.',
  confirm: 'Confirm',
  exclude: 'Exclude',
  restore: 'Restore',
  excluded: 'Excluded',
  confirmed: 'Ready',
  uncertain: 'Check card match',
  unreadable: 'Check limit break',
  conflict: 'Different LB readings. Correct or exclude one.',
  manual: 'Added manually',
  noFilterMatches: 'No cards match this filter.',
  download: 'Download inventory.json',
  preview: 'Preview JSON',
  summary: (owned: number, pending: number, duplicates: number, excluded: number) => [
    `${owned} unique card${owned === 1 ? '' : 's'}`, `${pending} to review`,
    `${duplicates} duplicate reading${duplicates === 1 ? '' : 's'} from overlap`, ...excluded ? [`${excluded} excluded`] : [],
  ].join(' · '),
  fileSummary: (cards: number, rare: number) => `${cards} reading${cards === 1 ? '' : 's'}${rare ? ` · ${rare} R cards ignored` : ''}`,
  exportBlocked: 'Resolve uncertain matches, unreadable diamonds, and conflicting readings before downloading.',
  noExport: 'Add screenshots or cards to create an inventory.',
  candidates: 'Suggested matches',
  source: 'Screenshot crop',
  reference: 'Reference artwork',
  // Prototype flow: three numbered steps, a decision-first review, and a bar that keeps the finish action in view.
  stepScreenshots: 'Screenshots',
  stepReview: 'Check readings',
  stepDownload: 'Download',
  stepApply: 'Apply to inventory',
  howTo: 'How to take screenshots',
  addMore: 'Add more',
  showScreenshots: 'Show screenshots',
  batchSummary: (files: number, readings: number, rare: number) => [
    `${files} screenshot${files === 1 ? '' : 's'}`, `${readings} reading${readings === 1 ? '' : 's'}`,
    ...rare ? [`${rare} R card${rare === 1 ? '' : 's'} ignored`] : [],
  ].join(' · '),
  decide: 'Needs a decision',
  allReady: (count: number) => `All ${count} card${count === 1 ? '' : 's'} read with confidence.`,
  ready: 'Read with confidence',
  readyHint: 'Open to check a reading or change a limit break.',
  excludedGroup: 'Excluded',
  unseen: 'Not seen in screenshots',
  unseenHint: 'Tap a card you own to add it.',
  seenIn: (count: number) => `Seen in ${count} screenshots`,
  lbBadge,
  useReading: (lb: number) => `Use ${lbBadge(lb)}`,
  setLb: 'Set limit break',
  barEmpty: 'No readings yet',
  barSummary: (ready: number, decide: number) => decide
    ? `${ready} ready · ${decide} to decide` : `${ready} ready`,
  apply: 'Apply to inventory',
  applied: (owned: number, unowned: number, changed: number) =>
    `Inventory updated: ${owned} marked owned, ${unowned} marked not owned, ${changed} limit breaks changed.`,
  modeReplace: 'Replace my inventory',
  modeReplaceHint: (unseen: number) => `SR and SSR cards not seen in any screenshot (${unseen}) become not owned.`,
  modeUpdate: 'Update only the cards that were read',
  modeUpdateHint: 'Every other card keeps its current value.',
  changeSummary: (owned: number, unowned: number, changed: number, unchanged: number) => [
    `${owned} newly owned`, `${unowned} marked not owned`, `${changed} limit break${changed === 1 ? '' : 's'} changed`,
    `${unchanged} unchanged`,
  ].join(' · '),
  noChanges: 'The readings match the current inventory.',
  closeScanner: '← Back to planner',
  subtitleEmbedded: 'Read support cards and limit breaks from screenshots, check the readings, then apply them to your inventory.',
  changeList: 'Show the cards',
  listOwned: 'Owned:',
  listChanged: 'Changed:',
  listUnowned: 'Not owned:',
  ownedAt: 'Owned at limit break',
  loadingScanner: 'Loading…',
  applyBlocked: 'Decide the remaining readings first.',
} as const;
